DO $$
BEGIN
  CREATE TYPE "ParentType" AS ENUM ('MOTHER', 'FATHER', 'GUARDIAN');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Parent"
ADD COLUMN IF NOT EXISTS "type" "ParentType" NOT NULL DEFAULT 'GUARDIAN';
